name: wisdom_jotter
description: Jotter App.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^5.0.0-release-candidate-4
  share_plus: ^7.0.2

  # share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
 
flutter:
  uses-material-design: true

assets:
  - assets/